import Head from "next/head";

type TaskType = {
  _id: number;
  name: string;
};

type HomePropsType = {
  tasks: TaskType[];
};

export default function Home({ tasks }: HomePropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
        <ul>
          {tasks.map((task) => (
            <li key={task._id}>{task.name}</li>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3001/api/tasks");
  const tasks = await response.json();

  return { props: { tasks } };
}
